# Generated by Django 3.0.5 on 2020-05-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.CharField(max_length=20, null=True, verbose_name='Slug'),
        ),
    ]
