# Generated by Django 3.0.5 on 2020-05-01 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ('usuario__first_name',), 'select_on_save': True, 'verbose_name': 'Perfil'},
        ),
    ]
