# Generated by Django 3.0.5 on 2020-05-02 00:10

import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200501_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='registro ativo')),
                ('quantidade', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=11, null=True, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.PositiveIntegerField(null=True, verbose_name='Peso do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(upload_to='produtos', validators=[core.validators.validate_file, core.validators.file_size], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='image',
            field=models.ImageField(upload_to='produtos', validators=[core.validators.validate_file, core.validators.file_size], verbose_name='Imagem'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, editable=False, verbose_name='registro ativo')),
                ('codigo', models.CharField(default=core.models.codigo, max_length=7, unique=True, verbose_name='Código')),
                ('itens', models.ManyToManyField(to='core.Item')),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
    ]
