# Generated by Django 3.0.5 on 2020-05-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='subcategoria',
            field=models.ManyToManyField(to='core.Categoria'),
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
