# Generated by Django 3.0.5 on 2020-05-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200501_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, to='core.Categoria'),
        ),
    ]
