# Generated by Django 3.0.5 on 2020-05-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200501_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_sub',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
