# Generated by Django 3.0.5 on 2020-05-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoria_is_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='is_sub',
            field=models.BooleanField(default=False, verbose_name='É subcategoria?'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_sub': True}, to='core.Categoria'),
        ),
    ]
