# Generated by Django 3.0.5 on 2020-05-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200501_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='is_sub',
            field=models.BooleanField(default=False, editable=False, verbose_name='É subcategoria?'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, to='core.Categoria'),
        ),
    ]
