# Generated by Django 3.0.5 on 2020-05-02 14:46

import cloudinary.models
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200501_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.validate_file, core.validators.file_size], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='image_500x500',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True, verbose_name='Imagem 500x500'),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.validate_file, core.validators.file_size], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='image_1000x1358',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True, verbose_name='Imagem 1000x1358'),
        ),
    ]
