# Generated by Django 3.0.5 on 2020-05-02 14:50

import cloudinary.models
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200502_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoimagem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[core.validators.validate_file, core.validators.file_size], verbose_name='Imagem'),
        ),
    ]
