# Generated by Django 3.0.5 on 2020-05-02 15:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200502_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image_500x500',
        ),
        migrations.RemoveField(
            model_name='produtoimagem',
            name='image_1000x1358',
        ),
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Imagem'),
        ),
    ]
