# Generated by Django 3.0.5 on 2020-05-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200502_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Slug'),
        ),
    ]
