# Generated by Django 3.0.5 on 2020-05-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200502_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(null=True, verbose_name='Descrição'),
        ),
    ]
