# Generated by Django 3.0.5 on 2020-05-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Slug'),
        ),
    ]
