# Generated by Django 3.0.5 on 2020-05-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(choices=[('#ffffff', 'Transparente / Branco'), ('#e63c3c', 'Vermelho'), ('#e6863c', 'Laranja'), ('#e6e33c', 'Amarelo'), ('#5ee63c', 'Verde'), ('#3ca8e6', 'Azul'), ('#993ce6', 'Roxo'), ('#e63cc4', 'Rosa'), ('#000000', 'Preto'), ('#b5b5b5', 'Cinza'), ('#5c4848', 'Marrom')], default='#ffffff', max_length=21, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=1, verbose_name='Estoque'),
        ),
    ]
