# Generated by Django 3.0.5 on 2020-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200505_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='Estoque'),
        ),
    ]
